### ISSUE TITLE
Available Models and Datasets

### ISSUE THREAD

**Issue by oldbulb** [MolecularAI/MolBART#30]
Hello! Thank you for your outstanding work.
May I ask if the trained models and datasets of Chemformer or MolBART could be available now? 
It would be so grateful if you can share them.

**Comment by EBjerrum** [comment]
Hello,
   We recently released the code for the chemformer paper and the pretrained model weights are available to download from box.  https://github.com/MolecularAI/Chemformer and https://az.app.box.com/s/7eci3nd9vy0xplqniitpk02rbg9q2zcq/folder/144879154710 

The model and weights for this project with Nvidia is currently being trained on Cambridge-1 cluster, so stay tuned.
