### ISSUE TITLE
Error with pysmilesutils and MolRandomizer

### ISSUE THREAD

**Issue by pribalta** [MolecularAI/MolBART#32]
Hi, I am trying to run the Molbart train script and I am having problems with `pysmilesutils`.

`molbart/data/datamodules.py` is using `MolRandomizer`, but in the `pysmilesutils` repo I can only see `MolAugmenter`. This is throwing an error that prevents from running the training.

Are you using an older version of library? If so, which one? I am trying to work around it by switching `MolRandomizer` to `MolAugmenter`, but no idea whether this will work. Any hints?

See below:

```
diff --git a/MolBART/molbart/data/datamodules.py b/MolBART/molbart/data/datamodules.py
index 3c2ad67..bc909f1 100644
--- a/MolBART/molbart/data/datamodules.py
+++ b/MolBART/molbart/data/datamodules.py
@@ -5,7 +5,7 @@ from rdkit import Chem
 from functools import partial
 from typing import List, Optional
 from torch.utils.data import DataLoader
-from pysmilesutils.augment import MolRandomizer
+from pysmilesutils.augment import MolAugmenter

 from molbart.tokeniser import MolEncTokeniser
 from molbart.data.util import TokenSampler
@@ -180,7 +180,7 @@ class MoleculeDataModule(_AbsDataModule):

         if augment:
             print("Using molecule data module with augmentations.")
-            self.aug = MolRandomizer()
+            self.aug = MolAugmenter()
         else:
             print("No molecular augmentation.")
             self.aug = None
@@ -328,7 +328,7 @@ class FineTuneReactionDataModule(_AbsDataModule):
             print("Training on backward prediction task.")

         self.augment = augment
-        self.aug = MolRandomizer() if augment is not None else None
+        self.aug = MolAugmenter() if augment is not None else None
         self.forward_pred = forward_pred

     def _collate(self, batch, train=True):
```

**Comment by SGenheden** [comment]
Hello,

Thanks for pointing this out. The `molbart` code indeed developed with an older version of `pysmilesutils`, and we neglected to update the code before it was pushed to Github.

The changes you have suggested, should work. The `MolRandomizer` class was renamed `MolAugmenter`.

If you can confirm that your script runs smoothly with the suggested changes, it would be great. Then we can prepare a patch for the code. Or if you would like to prepare a Pull request.

**Comment by pribalta** [comment]
The model seems to stop crashing after the change. Thank you for referring me to the Chemformer repository, I will stick with that for now.

I opened an MR in case you'd like to add this to your repo: https://github.com/MolecularAI/MolBART/pull/33
